package com.github.strogolsky.autoissue.core.output

/**
 * Interface for AI-generated issue candidates.
 *
 * Represents a potential issue that has been generated by the AI agent
 * and is ready for user review and editing before creation.
 *
 * Implementations may have additional fields beyond title and description
 * (e.g., JiraIssueCandidate adds labels, issue type, priority, etc.).
 */
interface IssueCandidate {
    /**
     * Issue summary/title (typically max 255 characters for JIRA).
     */
    val title: String

    /**
     * Detailed issue description in plain text.
     */
    val description: String
}
